# Generated by Django 3.0.6 on 2020-05-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceToVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('pass_confirm', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('activities', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.Activity')),
                ('places_to_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.PlaceToVisit')),
            ],
        ),
    ]
